"""Graph executor: invokes a compiled LangGraph graph with initial state.

thread_id and run_id are ALWAYS generated by the caller (RunService),
never inside this module — that would make them non-deterministic on replay.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import Any

from langchain_core.runnables.config import RunnableConfig
from langgraph.graph.state import CompiledStateGraph
from langgraph.types import Command

from app.runtime.state import RunState


@dataclass(slots=True, frozen=True)
class ExecutionResult:
    output: str | None
    # Set when the graph paused on a human-in-the-loop interrupt() call
    # instead of finishing — "paused for a decision" is not an error, so
    # this is a return value, not an exception.
    awaiting_approval: dict[str, Any] | None = None


async def execute_graph(
    compiled_graph: CompiledStateGraph[RunState, RunState, RunState],
    run_id: str,
    thread_id: str,
    user_input: str | None,
    deadline: float = 120.0,
    resume: bool = False,
    resume_value: Any = None,  # justified: mirrors langgraph.types.Command(resume=...)'s Any
    recursion_limit: int | None = None,
) -> ExecutionResult:
    """Invoke the compiled graph and return its output (or pause state).

    Args:
        compiled_graph: result of GraphCompiler.compile()
        run_id: UUID string of the Run record (for tracing inside handlers)
        thread_id: unique execution thread; the checkpoint key
        user_input: the human message that starts the conversation; ignored
            when resume=True (the checkpointer-resumed state already has it)
        deadline: seconds before asyncio.TimeoutError is raised
        resume: when True, continue from the last checkpoint on thread_id
            instead of starting a fresh run
        resume_value: when set (only meaningful if resume=True), the graph
            resumes via Command(resume=resume_value) instead of a bare
            ainvoke(None, ...) — this is how a human's approval/rejection
            decision is delivered to a paused interrupt() call. None means
            "no pending interrupt to answer", i.e. a plain crash-recovery resume.
        recursion_limit: caps LangGraph's internal step count. Must be sized
            from the graph's loop node(s) max_iterations (see
            GraphCompiler.compile's CompileResult.recursion_limit) — LangGraph's
            own default (25) is far too low for a legitimate multi-iteration
            loop and would raise GraphRecursionError before the loop's own
            cap is ever reached. None falls back to LangGraph's default, which
            is only safe for loop-free graphs.

    Returns:
        ExecutionResult with the final output, or with awaiting_approval set
        if the graph paused on a human-in-the-loop interrupt() call.
    """
    config: RunnableConfig = {"configurable": {"thread_id": thread_id}}
    if recursion_limit is not None:
        config["recursion_limit"] = recursion_limit

    graph_input: RunState | Command[Any] | None
    if resume:
        graph_input = Command(resume=resume_value) if resume_value is not None else None
    else:
        assert user_input is not None, "user_input is required for a fresh (non-resume) run"
        graph_input = {
            "run_id": run_id,
            "messages": [{"role": "user", "content": user_input}],
            "output": None,
            "step_index": 0,
            "error": None,
            "loop_counters": {},
            "loop_continue": {},
        }

    async with asyncio.timeout(deadline):
        raw: Any = await compiled_graph.ainvoke(graph_input, config)
    result: dict[str, Any] = raw

    interrupts = result.get("__interrupt__")
    if interrupts:
        return ExecutionResult(output=None, awaiting_approval=interrupts[0].value)
    return ExecutionResult(output=result.get("output"))
