"""Graph executor: invokes a compiled LangGraph graph with initial state.

thread_id and run_id are ALWAYS generated by the caller (RunService),
never inside this module — that would make them non-deterministic on replay.
"""

from __future__ import annotations

import asyncio
from typing import Any

from langchain_core.runnables.config import RunnableConfig
from langgraph.graph.state import CompiledStateGraph

from app.runtime.state import RunState


async def execute_graph(
    compiled_graph: CompiledStateGraph[RunState, RunState, RunState],
    run_id: str,
    thread_id: str,
    user_input: str,
    deadline: float = 120.0,
) -> str | None:
    """Invoke the compiled graph and return the final output string.

    Args:
        compiled_graph: result of GraphCompiler.compile()
        run_id: UUID string of the Run record (for tracing inside handlers)
        thread_id: unique execution thread; will be the checkpoint key in Phase 4
        user_input: the human message that starts the conversation
        deadline: seconds before asyncio.TimeoutError is raised

    Returns:
        The final assistant answer, or None if no output node produced content.
    """
    initial_state: RunState = {
        "run_id": run_id,
        "messages": [{"role": "user", "content": user_input}],
        "output": None,
        "step_index": 0,
        "error": None,
    }
    # configurable thread_id is the checkpoint key; Phase 4 will attach the
    # checkpointer here — no other change required in this function.
    config: RunnableConfig = {"configurable": {"thread_id": thread_id}}

    async with asyncio.timeout(deadline):
        raw: Any = await compiled_graph.ainvoke(initial_state, config)
    result: dict[str, Any] = raw
    return result.get("output")
