"""add run awaiting_approval flag

Revision ID: 3a58679fe583
Revises: d354665d69e7
Create Date: 2026-06-17 23:29:39.175511
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3a58679fe583"
down_revision: str | None = "d354665d69e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required so ADD COLUMN ... NOT NULL succeeds against a
    # non-empty runs table (existing rows backfill to False).
    op.add_column(
        "runs",
        sa.Column("awaiting_approval", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "awaiting_approval")
    # ### end Alembic commands ###
